### PR TITLE
0.3/0.4 compatability

### PR DESCRIPTION
**Pull request by samtkaplan**
Hello,

This uses the Compat.jl package to make Lumberjack compatible with both 0.3 and 0.4 versions of Julia.  I hope it is useful.

Thanks!

Sam

### CODE REVIEW

**Comment by WestleyArgentum** [comment]
Hey, thanks so much! Sorry for the delay!

**Comment by samtkaplan** [comment]
Hi Westley,

Thanks for merging!  I just realized that Travis is only testing with a Julia 0.4 environment.  I don't have much experience with Travis, but I suppose we should be able to configure it to test against 0.3 and 0.4.  I'll try to find some time (maybe next weekend) to fiddle with it.

Sam

**Comment by WestleyArgentum** [comment]
Hey, no worries! This package is old enough that it's using a hand-made travis script, probably we need to copy the one that comes with new packages. I'll also make an attempt to fix it soon, so that we can tag and publish these compatibility changes.

**Comment by WestleyArgentum** [comment]
I just finished working through the travis stuff and a couple other minor things that came up. There's a pr in metadata open here: https://github.com/JuliaLang/METADATA.jl/pull/2810 I'll merge as soon as it passes.

**Pull request merged**
