### PR TITLE
update to v0.4

### PR DESCRIPTION
**Pull request by compressed**
Hi,
I made some changes to update to julia 0.4. Not sure if backwards compatibility is important for you or not.. We can do that with https://github.com/JuliaLang/Compat.jl if needed. We'll need a version check on `using Dates` as well in `Lumberjack.jl`.

Let me know.

Thanks!

### CODE REVIEW

**Comment by WestleyArgentum** [comment]
I'm so so sorry, I totally forgot about this! Thanks so much!

If we need to release another 0.3 version I'm sure we can use Compat.jl to make it work.

**Comment by WestleyArgentum** [comment]
I'll publish in metadata later today

**Comment by WestleyArgentum** [comment]
Published! Thanks again!

**Comment by compressed** [comment]
Great thanks!

**Pull request merged**
